version: "3"

services:
  navigation:
    image: "llabhishekll/cafeteriabot_project:ros2-base"
    command: ["ros2", "launch", "cafeteriabot_navigation", "navigation_server.launch.py", "use_sim_time:=False"]
    networks:
      - default
    environment:
      - "ROS_DOMAIN_ID=0"
    tty: true
  
  detection:
    image: "llabhishekll/cafeteriabot_project:ros2-base"
    command: ["ros2", "launch", "cafeteriabot_firmware", "detection_server.launch.py", "use_sim_time:=False"]
    networks:
      - default
    environment:
      - "ROS_DOMAIN_ID=0"
    tty: true
  
  control:
    image: "llabhishekll/cafeteriabot_project:ros2-base"
    command: ["ros2", "launch", "cafeteriabot_firmware", "cafeteriabot_control.launch.py", "use_sim_time:=False"]
    networks:
      - default
    environment:
      - "ROS_DOMAIN_ID=0"
    tty: true

networks:
  default:
    driver: bridge