behavior_tree_node:
  ros__parameters:
    use_sim_time: False
    global_frame: "map"
    robot_base_frame: "cleaner_2/base_link"
    odom_topic: "/odom"
    bt_loop_duration: 10
    default_server_timeout: 20
    default_nav_to_pose_bt_xml: "behavior_tree.xml"
    default_nav_through_poses_bt_xml: "behavior_tree.xml"
    navigators: ['navigate_to_pose', 'navigate_through_poses']
    navigate_to_pose:
      plugin: "nav2_bt_navigator/NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator/NavigateThroughPosesNavigator"