costmap_filter_info_node:
  ros__parameters:
    use_sim_time: False
    filter_info_topic: "/costmap_filter_info"
    type: 0
    mask_topic: "/keepout_filter_mask"
    base: 0.0
    multiplier: 1.0

filter_mask_node:
  ros__parameters:
    use_sim_time: False
    frame_id: "map"
    topic_name: "/keepout_filter_mask"
    yaml_filename: "map_keepout_mask.yaml"