simulation:
  patrol:
    - [0.5, 0.0, -1.57]
    - [0.5, -1.5, -3.14]
    - [-1.0, -1.5, -3.14]
    - [-2.5, -1.5, -3.14]
    - [-1.0, -1.5, 0.0]
    - [0.5, -1.5, 0.0] # center
    - [2.0, -1.5, 0.0]
    - [3.5, -1.5, -3.14]
    - [2.0, -1.5, -3.14]
    - [0.5, -1.5, 1.57]
  home_to_drop:
    - [0.5, 0.0, -1.57]
    - [0.5, -1.5, -3.14]
    - [-1.0, -1.5, -3.14]
    - [-2.5, -1.5, -3.14]
  drop_to_home:
    - [-1.0, -1.5, 0.0]
    - [0.5, -1.5, 1.57]
    - [0.5, 0.0, 1.57]
    - [0.0, 0.0, 0.0]

real:
  patrol:
    - [1.5, 0.0, 0.0]
    - [3.0, 0.0, 0.0]
    - [4.0, -1.0, 0.0]
    - [5.5, -1.0, 0.0]
    - [5.5, 0.0, 1.57]
    - [5.5, -1.0, -3.14]
    - [4.0, -1.0, -3.14]
    - [3.0, 0.0, -3.14]
    - [1.5, 0.0, -3.14]
  home_to_drop:
    - [1.0, 0.0, -2.61]
    - [0.3, -0.80, -3.14]
    - [-1.0, -0.75, -3.14]
    - [-1.5, 0.0, 1.57]
    - [-1.5, 1.0, 1.57]
  drop_to_home:
    - [-1.5, 0.0, -1.57]
    - [-1.0, -0.75, 0.0]
    - [0.3, -0.80, 0.52]
    - [1.0, 0.0, -3.14]