simulation:
  home:
    - [0.0, 0.0, 0.0]
  drop:
    - [-2.5, -1.5, 0.0]
  patrol:
    - [0.5, 0.0, 0.0]
    - [0.5, -1.5, 0.0]
    - [-1.0, -1.5, 0.0]
    - [-2.5, -1.5, 0.0]
    - [-1.0, -1.5, 0.0]
    - [0.5, -1.5, 0.0] # center
    - [2.0, -1.5, 0.0]
    - [3.5, -1.5, 0.0]
    - [2.0, -1.5, 0.0]
    - [0.5, -1.5, 0.0]
    - [0.5, 0.0, 0.0]
  home_to_drop:
    - [0.5, 0.0, 0.0]
    - [0.5, -1.5, 0.0]
    - [-1.0, -1.5, 0.0]
    - [-2.5, -1.5, 0.0]
  drop_to_home:
    - [-1.0, -1.5, 0.0]
    - [0.5, -1.5, 0.0]
    - [0.5, 0.0, 0.0]
    - [0.0, 0.0, 0.0]

real:
  home:
    - [0.0, 0.0, 0.0]
  drop:
    - [0.0, 0.0, 0.0]
  patrol:
    - [0.0, 0.0, 0.0]
  home_to_drop:
    - [0.0, 0.0, 0.0]
  drop_to_home:
    - [0.0, 0.0, 0.0]
